### ISSUE TITLE
fix dependency hell

### ISSUE THREAD

**Issue by antonkulaga** [denigma/plasmid-bank#12]
У меня какая-то фигня с зависимостями, травис не может отрезовлить некоторые зависимости, хотя резолверы я все добавил и наличие либ проверил. @rmihael , буду благодарен, если попробуешь забилдить PR и запустить (через re-start) у себя на машине и посмотреть нет ли у тебя траблов. Я реально не могу понять что за ерунда происходит.

**Comment by rmihael** [comment]
Могу подтвердить, что на чистом клоне репоза билд не проходит. Ругается так: https://gist.github.com/rmihael/003cfa5d25765298c655

**Comment by antonkulaga** [comment]
Хорошо, сегодня у меня эксперименты, завтра достану бубен и sbt dependency graph и буду смотреть что не так тянется.  Но вообще странно, что не учитывается резолвер сбтшный

**Comment by antonkulaga** [comment]
Пофиксил зависимости. Теперь всё красивым цветом зеленеет в Трависе.
